#spring.application.name=241DSWSpringMSDemo01Preguntas
server:
  port: 9091
spring:
  application:
    name: 241DSWSpringMSDemo01Preguntas
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dswg13
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka