#spring.application.name=241DSWSpringMSDemo01Persona
server:
  port: 7090
spring:
  application:
    name: 241DSWSpringMSDemo01Persona
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cp4hkgi1hbls73f20ef0-a.oregon-postgres.render.com/dswg13
    username: fabrizic
    password: TNj77P50Dvd4KHdDp4ZRCr9nFKFlKLsh
  jpa:
    hibernate:
      ddl-auto: update
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect      

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
